FROM python:3.10-slim

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt -i https://repo.huaweicloud.com/repository/pypi/simple --trusted-host repo.huaweicloud.com

COPY . .

EXPOSE 5000

WORKDIR /app

CMD ["python", "app.py"]