version: '3.3'
services:
  mysql:
    build:
      context: .
      dockerfile: docker/db/dockerfile
      args:
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    platform: linux/amd64
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  backend:
    build:
      context: .
      dockerfile: docker/backend/dockerfile
    platform: linux/amd64
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - HOST_IP=${HOST_IP}
      - HOST_PORT=${HOST_PORT}
    depends_on:
      mysql:
        condition: service_healthy

