version: '3.3'
services:
  mysql:
    image:  swr.cn-north-4.myhuaweicloud.com/seat-reservation-system/backend_db:[VERSION]
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  backend:
    image:  swr.cn-north-4.myhuaweicloud.com/seat-reservation-system/backend_backend:[VERSION]
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - HOST_IP=${HOST_IP}
      - HOST_PORT=${HOST_PORT}
      - APPID=${APPID}
      - SECRET=${SECRET}
    depends_on:
      mysql:
        condition: service_healthy

