# cat Dockerfile
FROM swr.cn-north-4.myhuaweicloud.com/seat-reservation-system/mysql:8.4.0

ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_ROOT_PASSWORD

ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
ENV MYSQL_ALLOW_EMPTY_PASSWORD=true

ADD ./sql/create_all_table.sql /etc/mysql/data.sql

RUN cp /etc/mysql/data.sql /docker-entrypoint-initdb.d

EXPOSE 3306