# File: .github/workflows/repo-sync.yml

on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo:  "https://private-token:${{ secrets.TOKEN }}@codehub.devcloud.cn-north-4.huaweicloud.com/8ac6cbe6f41648a3a757004f3e2e6ed0/Backend.git"
        source_branch: "*"
        destination_branch: "*"
        github_token: ${{ secrets.PAT }}